// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3tLlSxJydHOoLGF02lAL2Cdu14hSWXe0',
    appId: '1:938877453735:android:584043f15f0bd5edaee282',
    messagingSenderId: '938877453735',
    projectId: 'deenmate-be588',
    storageBucket: 'deenmate-be588.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfW5y7y3PLvRAWB0Xrh9PXEPVdgXzriuQ',
    appId: '1:938877453735:web:c627ff6f9a697bc9aee282',
    messagingSenderId: '938877453735',
    projectId: 'deenmate-be588',
    authDomain: 'deenmate-be588.firebaseapp.com',
    storageBucket: 'deenmate-be588.firebasestorage.app',
    measurementId: 'G-61Q4DBTFHR',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6dagD8-gnMErxTDpQLK9ftkvWc-M6gjA',
    appId: '1:938877453735:ios:70dbe53129d4b260aee282',
    messagingSenderId: '938877453735',
    projectId: 'deenmate-be588',
    storageBucket: 'deenmate-be588.firebasestorage.app',
    androidClientId: '938877453735-02b9bu30jf6vtnam6otatevc63jb9au8.apps.googleusercontent.com',
    iosClientId: '938877453735-6ebilga7itu3mp9na7n952h5lgrlkbhm.apps.googleusercontent.com',
    iosBundleId: 'com.example.deenmateSdp2',
  );
}
